# Config file for build_idf_examples.yml workflow

paths = [
    "examples/peripherals/usb/device",      # USB Device examples
    #"examples/network/sta2eth",             # USB Network example
]

manifest_files = [
    "examples/peripherals/.build-test-rules.yml",
    "examples/network/.build-test-rules.yml",
]

recursive = true
check_warnings = true
target = "all"
#enable_preview_targets = true

# build related options
build_dir = "build_@t"
